 
        
         <header class=" clearfix">
        <div class="row flex-nowrap justify-content-between align-items-center">
            <div class="col-4 pt-1">

            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><img
                        src="<?php echo $this->themeSettingAssetUrl('logo'); ?>"  class="col-12" title="Logo"></a>
                <?php
else: ?>
                <a href="<?php echo $site->url(); ?>"
                    class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                <?php
endif; ?>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">

            </div>
        </div>
        <div class="nav-scroller py-1 mb-2">
            <nav class="navbar navbar-expand-lg navbar-light">

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse  mx-center" id="navbarSupportedContent">
                    <?php echo $site->publicNav()->menu()->renderMenu(null, ['maxDepth' => $this->themeSetting('nav_depth') - 1]);
?>
                </div>

            </nav>
        </div>

    </header>
    