 
         <header class=" clearfix">
         
         <div class="row flex-nowrap  text-center align-items-center">
          
            <div class="col-12 text-center">
                <?php if ($this->themeSetting('logo')): ?>
                <a  href="<?php echo $site->url(); ?>"  ><img
                class="col-6" src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php
else: ?>
                <a href="<?php echo $site->url(); ?>"
                    class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                <?php
endif; ?>
            </div>

            
            
        </div>
 

    </header>
    