<?php $escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width,
initial-scale=1'); $this->headTitle($this->setting('installation_title', 'Omeka
S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css',
'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/octoroon.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/bootstrap.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/popper.min.js'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js',
'Omeka')); $this->trigger('view.layout'); $title =
$this->pageTitle($site->title()); $userBar = $this->userBar(); $logo =
$this->themeSettingAssetUrl('logo'); if ($logo): $title = '<img src="' .
$this->escapeHtml($logo) . '">'; endif; ?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body'); ?>

<?php echo $userBar; ?>

<?php if (strpos($_SERVER['REQUEST_URI'], 'welcome') !== false): ?>
<!--homeage if is called welcome  ---->

<div class="site-wrapper bg">
    <div class="site-wrapper-inner ">
   
    <div class="nav-scroller py-1 mb-2">
        
        </div>
        <div class="cover-container">
            <?php include ('_includes/header-home.phtml') ;?>
            <!--content pages ---->
            <main id="content" role="main" class="inner cover">
                <div class="container">
                    <?php echo $this->content; ?>
                    
                </div>
            </main>
            <!--end content pages ---->
            <?php include ('_includes/footer.phtml') ;?>
        </div>
    </div>
</div>
<!--end homepage - welcome -->
<?php
elseif (strpos($_SERVER['REQUEST_URI'], 'other-page') !== false): ?>

<?php
else: ?>
<div id="all-content" class="site-wrapper">

    <div class="site-wrapper-inner">

        <div class="container-fluid no-paddding">
            <?php include ('_includes/header.phtml') ;?>
        </div>    
            <!--content pages ---->
            <div class="container">
            <main id="content" role="main">
                <div class="container">
                    <?php echo $this->content; ?>
                </div>
            </main>
            <!--end content pages ---->

            <?php include ('_includes/footer.phtml') ;?>
        </div>
    </div>
</div>
<?php
endif; ?>

</body>

</html>